### ISSUE TITLE
유니코드 인코딩 파일을 읽지 못하는 이슈

### ISSUE THREAD

**Issue by Sharku2011** [sublee/korean#18]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sharku\AppData\Roaming\Python\Python38\site-packages\korean\__init__.py", line 54, in <module>
    _load_data()
  File "C:\Users\Sharku\AppData\Roaming\Python\Python38\site-packages\korean\__init__.py", line 39, in _load_data
    data = json.load(f)
  File "C:\Program Files\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 36: illegal multibyte sequence
```

pip를 통해 설치된 버전이 옛날 버전이라서 발생한것 같네요. 티켓 종료하겠습니당

**Comment by Sharku2011** [comment]
앗 ㅈ
